### ISSUE TITLE
contents text color

### ISSUE THREAD

**Issue by iRobertas** [LinusU/node-appdmg#144]
Hello, is it possible to change contents text color ? Example "Applications" is black, can I change it to other color ?

**Comment by ndreisg** [comment]
That would be a nice feature since it would allow to use a dark background, but I don't think it is currently supported. (@LinusU correct me if I'm wrong)
With Mojave's new "Dark Mode" captions in finder are black or white depending on the current mode so adding this should probably be possible.

As a workaround you can add a colored background behind the content like in the sample background.

**Comment by LinusU** [comment]
Unfortunately, I don't think there's a way to do this.

I'd be happy to re-open if someone can show me a DMG that does this, or provide some insight into how this would be achieved ☺️
