### ISSUE TITLE
Window position

### ISSUE THREAD

**Issue by sagendejonge** [LinusU/node-appdmg#53]
Is there any way to define the position where the window pops up?  Right now it's showing up in the bottom left region and would like to change it to the top center.

**Comment by LinusU** [comment]
This could be accomplished with `file.setWindowPos(x, y)` of `ds-store`. Should be inserted somewhere around [lib/appdmg.js line 389](https://github.com/LinusU/node-appdmg/blob/1e631c35dc1c719e3738dd1a9b32dd608b7c953c/lib/appdmg.js#L389).

The specification could take a `"window-position": { "x": n, "y": n }` or maybe `"window-pos": [n, n]`...

**Comment by sagendejonge** [comment]
Perfect thanks.  Would be great to add something like that to the spec.

**Comment by iRobertas** [comment]
Anyone managed to change window position ? Because for me its not working, I added file.setWindowPos(x, y) to lib/appdmg.js line 389, tried to add "window-position": { "x": n, "y": n } and "window-pos": [n, n] to property file, but in both cases I get "[exec] ReferenceError: file is not defined"

[exec] [ 1/20] Looking for target...                [ OK ]
[exec] [ 2/20] Reading JSON Specification...        [ OK ]
[exec] [ 3/20] Parsing JSON Specification...        [ OK ]
[exec] [ 4/20] Validating JSON Specification...     [ OK ]
[exec] [ 5/20] Looking for files...                 [ OK ]
[exec] [ 6/20] Calculating size of image...         [ OK ]
[exec] [ 7/20] Creating temporary image...          [ OK ]
[exec] [ 8/20] Mounting temporary image...          [ OK ]
[exec] [ 9/20] Making hidden background folder...   [ OK ]
[exec] [10/20] Copying background...                [ OK ]
[exec] [11/20] Reading background dimensions...     [ OK ]
[exec] [12/20] Copying icon...                      [ OK ]
[exec] [13/20] Setting icon...                      [ OK ]
[exec] [14/20] Creating links...                    [ OK ]
[exec] [15/20] Copying files...                     [ OK ]
[exec] [16/20] Making all the visuals...            
[exec] ReferenceError: file is not defined

**Comment by LinusU** [comment]
Should be `ds.setWindowPos(_, _)` at [lib/appdmg.js line 358](https://github.com/LinusU/node-appdmg/blob/68e5b9bbe7ac188c11d668fbff5458cc0c7a0fb8/lib/appdmg.js#L358) now

**Comment by ndreisg** [comment]
Will this option behave the same on different screen resolutions?
When I center my image on my iMac will it still be centered on a MacBook Air?
