### ISSUE TITLE
Installing the application for user, instead of root.

### ISSUE THREAD

**Issue by apigarage** [LinusU/node-appdmg#70]
Hi there,

I tried installing the app for the user using the configuration below. 
```
{
  "title": "{{productName}}",
  "icon": "{{dmgIcon}}",
  "background": "{{dmgBackground}}",
  "icon-size": 128,
  "contents": [
    { "x": 410, "y": 220, "type": "link", "path": "~/Applications" }, // <-- concerned changes
    { "x": 130, "y": 220, "type": "file", "path": "{{appPath}}" }
  ]
}
```

But, when I install the app and try to drag the application icon to ~/Applications folder, it does not let me. It shows the cursor with not allowed symbol. Any idea, how I can resolve it?

**Comment by LinusU** [comment]
As far as I know, this isn't possible :(

I think that this has been brought up before, but basically the problem is that you won't know the name of the user that is going to use it in advance, so there is nothing you can write in the link to make it work.

Unfortunately I cannot help you with this, the only possibility that I see, and it's a slim one, is that there is some way to use the alias format for that. I'm not sure if it's possible thought...

**Comment by apigarage** [comment]
Hi Linus,

Thanks for your answer. Will try to figure something out.
