### ISSUE TITLE
Why is it the application is ejectable instead of the dmg after extracting it

### ISSUE THREAD

**Issue by tbaranes** [LinusU/node-appdmg#71]
Everything is working well, it's just about a behaviour I find strange. The scenario is easy:
1 - Generates a dmg containing any app
2 - Open the dmg
3 - You will have now on your mac desktop the application (ejectable)

Generally speaking, after opening a dmg, the dmg is staying in the desktop, and the user have to eject it manually.  So, why when using node-appdmg, we have to eject the application instead of the dmg? Did I miss something?

**Comment by LinusU** [comment]
I don't really understand the problem...

The icon that you specify in the json-specification is the icon for the dmg. Could it be that you are confusing that with your application?

**Comment by tbaranes** [comment]
Sorry, I will try to be more clear.

I will make the steps with the example of the repot:

First, mounting the dmg (everything working well):

<img width="440" alt="screen shot 2015-10-20 at 13 38 39" src="https://cloud.githubusercontent.com/assets/1402212/10606015/0fe8b0fa-7730-11e5-9ffa-a32321ddac94.png">

After opening the dmg, we will have:
- The icon of the application
- The "Test Title" window

<img width="811" alt="screen shot 2015-10-20 at 13 42 10" src="https://cloud.githubusercontent.com/assets/1402212/10606049/614ac24e-7730-11e5-8b68-9633bc04a6b4.png">

And my question is: why do we have the application on our desktop after opening the dmg? Shouldn't be the dmg directly? I mean, generally, after opening a dmg, we have to "eject" the dmg, not the application?

So in the following screenshot, the "ejectable" file should be the dmg, isn't it? 

<img width="294" alt="screen shot 2015-10-20 at 13 43 06" src="https://cloud.githubusercontent.com/assets/1402212/10606071/821eb8ae-7730-11e5-8eda-d7b05ac29618.png">

Hoping it's more clear :)

**Comment by ekryski** [comment]
This confused me as well. @tbaranes that's not the application, it **is** the DMG mount. The icon you've specified in your json config is used for both.

However, as a follow up to that, @LinusU is it possible to assign a separate image to the mounted DMG so that it doesn't look like the application?

**Comment by tbaranes** [comment]
Oh right, I misunderstand the fact that the icon is used for the application as well as the dmg mount... I think it can confused the users too, so it could be great to have the possibility to assign a separate image to the mount dmg.

**Comment by LinusU** [comment]
The icon *is not* used for the application. That would be very weird since you can copy whatever files into the dmg as you want, what would happen if I added two applications?

The `icon` option *only* affects which icon is used for the dmg not the application(s), and the `title` option *only* affects the name of the dmg not the application(s).

> ...so it could be great to have the possibility to assign a separate image to the mount dmg.

That possibility exist, actually it's the only thing you can do with the `icon` option.

Is this good or do you feel that the documentation is lacking? Maybe we could make it more clear somehow?

**Comment by tbaranes** [comment]
> Is this good or do you feel that the documentation is lacking? Maybe we could make it more clear somehow?

Yeah, I think the documentation should be improved to avoid this kind of misunderstanding. I suggest:
- It will probably be too big breaking change, but the best way to improve it would be to change "icon" to "dmg-icon". 
- When you are talking about the "icon", replace it by "dmg-icon", are something like that...
- In the demo project, change a little bit the dmg icon in order to make a difference in comparison with the app's icon

In fact, I think the last point will be enough.

Anyway, thanks for the explanation, just try out, everything is clear for me now. Moreover, that's great because I was thinking to ask you how to change the dmg icon!

**Comment by ekryski** [comment]
Oh ok, that makes sense. Thanks @LinusU for clarifying.
